# Generated by Django 3.0.4 on 2020-05-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_bool',
            field=models.BooleanField(default=False),
        ),
    ]
