# Generated by Django 3.0.4 on 2020-04-18 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0002_auto_20200417_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
