# Generated by Django 2.2.6 on 2020-05-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0002_auto_20200505_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
