# Generated by Django 3.0.4 on 2020-05-06 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0002_auto_20200505_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='followers',
            new_name='follower',
        ),
        migrations.RemoveField(
            model_name='follows',
            name='followee',
        ),
    ]
