# Generated by Django 2.2.12 on 2020-04-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0002_auto_20200417_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='gsplit/images/1.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_html',
            field=models.ImageField(default='gsplit/images/1.jpg', editable=False, upload_to=''),
        ),
    ]
