# Generated by Django 3.0.4 on 2020-05-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0002_post_comment_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_bool',
        ),
    ]
