# Generated by Django 3.0.4 on 2020-05-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0003_auto_20200505_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='follower',
        ),
        migrations.AddField(
            model_name='follows',
            name='followee',
            field=models.ManyToManyField(related_name='Follows', to='gsplit.Follows'),
        ),
    ]
