# Generated by Django 3.0.4 on 2020-05-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0003_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
    ]
