# Generated by Django 3.0.4 on 2020-05-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0006_follows_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='follows',
            field=models.ManyToManyField(related_name='follow_pair', to='gsplit.UserProfile'),
        ),
    ]
