# Generated by Django 3.0.5 on 2020-04-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0006_auto_20200419_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
    ]
