# Generated by Django 3.0.5 on 2020-04-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0007_remove_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
