# Generated by Django 3.0.4 on 2020-05-06 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0007_auto_20200506_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='follows',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gsplit.UserProfile'),
        ),
    ]
