# Generated by Django 3.0.4 on 2020-05-06 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0008_follows_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follows',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='follows',
            name='profile',
        ),
        migrations.AddField(
            model_name='follows',
            name='followee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gsplit.UserProfile'),
        ),
        migrations.AddField(
            model_name='follows',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gsplit.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(related_name='_userprofile_followers_+', through='gsplit.Follows', to='gsplit.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='_userprofile_following_+', through='gsplit.Follows', to='gsplit.UserProfile'),
        ),
    ]
