# Generated by Django 3.0.5 on 2020-04-19 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0008_remove_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
