# Generated by Django 3.0.4 on 2020-05-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0011_like_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='usr',
        ),
    ]
