# Generated by Django 3.0.4 on 2020-05-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0012_auto_20200506_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='usr',
            new_name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='like_f',
            field=models.ManyToManyField(related_name='_post_like_f_+', through='gsplit.Like', to='gsplit.Post'),
        ),
    ]
