# Generated by Django 2.2.6 on 2020-04-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0012_auto_20200419_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
