# Generated by Django 3.0.4 on 2020-05-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0014_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
