# Generated by Django 3.0.4 on 2020-05-10 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0014_auto_20200506_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.ManyToManyField(related_name='_post_post_+', to='gsplit.Post'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked',
            field=models.ManyToManyField(related_name='_userprofile_liked_+', to='gsplit.UserProfile'),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gsplit.UserProfile')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gsplit.Post')),
            ],
        ),
    ]
