# Generated by Django 3.0.6 on 2020-05-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0015_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
