# Generated by Django 3.0.4 on 2020-05-01 06:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0015_auto_20200430_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b82a5c24-f0ff-4033-8b75-9c1c7d5a7400'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
