# Generated by Django 3.0.4 on 2020-05-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0015_auto_20200510_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='liked',
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(related_name='_post_liked_+', to='gsplit.Post'),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
