# Generated by Django 3.0.4 on 2020-05-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0016_auto_20200510_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(to='gsplit.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
