# Generated by Django 3.0.4 on 2020-05-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0017_auto_20200510_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
