# Generated by Django 3.0.6 on 2020-05-11 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0017_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
