# Generated by Django 3.0.4 on 2020-05-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0018_auto_20200501_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pid',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
