# Generated by Django 2.2.12 on 2020-05-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0020_auto_20200502_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text_html',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
