# Generated by Django 2.2.12 on 2020-05-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0023_auto_20200504_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default="We see you haven't made your profile yet. Go ahead and edit your profile with your information !"),
        ),
    ]
