# Generated by Django 2.2.12 on 2020-05-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0024_auto_20200504_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/BlueHead.jpg', null=True, upload_to='images/'),
        ),
    ]
