# Generated by Django 2.2.12 on 2020-05-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsplit', '0025_auto_20200504_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='BlueHead.jpg', null=True, upload_to='images/'),
        ),
    ]
